# Generated by Django 2.2.6 on 2019-11-20 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Providers',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Provider')),
            ],
            options={
                'verbose_name': 'ProductProvider',
                'verbose_name_plural': 'ProductProviders',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='providers',
            field=models.ManyToManyField(related_name='products', through='product.ProductProvider', to='product.Provider'),
        ),
    ]
